# Generated by Django 4.2.8 on 2024-01-01 09:24

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityImpactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('testimonials', wagtail.fields.RichTextField(blank=True)),
                ('statistics_and_achievements', wagtail.fields.RichTextField(blank=True)),
                ('community_feedback', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Community Impact Page',
                'verbose_name_plural': 'Community Impact Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
