# Generated by Django 4.2.8 on 2024-01-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0003_alter_communityfeedback_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityfeedback',
            name='approved',
            field=models.BooleanField(auto_created=True, default=False),
        ),
    ]
