# Generated by Django 4.2.8 on 2024-03-07 13:21

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('impact', '0005_alter_communityfeedback_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityimpactpage',
            old_name='statistics_and_achievements',
            new_name='statistics_and_achievements_intro',
        ),
        migrations.RenameField(
            model_name='communityimpactpage',
            old_name='testimonials',
            new_name='testimonials_intro',
        ),
        migrations.CreateModel(
            name='StatisticsAndAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', wagtail.fields.RichTextField()),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics_and_achievements', to='impact.communityimpactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
