# Generated by Django 5.0 on 2023-12-31 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutuspage',
            options={'verbose_name': 'About us Page', 'verbose_name_plural': 'About us Pages'},
        ),
    ]
