# Generated by Django 5.0 on 2023-12-31 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0004_alter_staffimages_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffimages',
            old_name='staff_bios',
            new_name='bios',
        ),
        migrations.RenameField(
            model_name='staffimages',
            old_name='staff_name',
            new_name='name',
        ),
    ]
