# Generated by Django 5.0 on 2023-12-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0005_rename_staff_bios_staffimages_bios_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffimages',
            old_name='bios',
            new_name='staff_bios',
        ),
        migrations.RenameField(
            model_name='staffimages',
            old_name='name',
            new_name='staff_name',
        ),
        migrations.RenameField(
            model_name='staffimages',
            old_name='photo',
            new_name='staff_photo',
        ),
        migrations.AddField(
            model_name='staffimages',
            name='staff_title',
            field=models.CharField(default='member', max_length=150),
        ),
    ]
