# Generated by Django 5.0 on 2023-12-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0006_rename_bios_staffimages_staff_bios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffimages',
            name='staff_title',
            field=models.CharField(default='Member', max_length=150),
        ),
    ]
