# Generated by Django 5.0 on 2023-12-31 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0007_alter_staffimages_staff_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffimages',
            old_name='staff_bios',
            new_name='bios',
        ),
        migrations.RenameField(
            model_name='staffimages',
            old_name='staff_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='staffimages',
            old_name='staff_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='staffimages',
            old_name='staff_title',
            new_name='title',
        ),
    ]
