# Generated by Django 5.0 on 2023-12-31 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0008_rename_staff_bios_staffimages_bios_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutuspage',
            options={'verbose_name': 'About Us Page', 'verbose_name_plural': 'About Us Pages'},
        ),
    ]
