# Generated by Django 4.2.8 on 2023-12-31 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0009_alter_aboutuspage_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffimages',
            old_name='photo',
            new_name='image',
        ),
    ]
