# Generated by Django 4.2.8 on 2024-03-06 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogindexpage',
            options={'verbose_name': 'Blog Page', 'verbose_name_plural': 'Blog Pages'},
        ),
        migrations.RenameField(
            model_name='blogindexpage',
            old_name='updates_on_initiatives',
            new_name='intro',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='community_stories',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='news_and_articles',
        ),
    ]
