# Generated by Django 5.0 on 2023-12-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_welcome_homepage_intro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='current_initiatives',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='overview',
        ),
    ]
