# Generated by Django 5.0 on 2023-12-28 08:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_current_initiatives_homepage_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='current_initiatives',
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='overview',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
