# Generated by Django 5.0 on 2023-12-31 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_currentinitiativeimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page', 'verbose_name_plural': 'Home Pages'},
        ),
    ]
