# Generated by Django 4.2.8 on 2023-12-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_current_initiatives_homepage_current_initiatives_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentinitiativeimage',
            name='initiative_title',
            field=models.CharField(default='Books Distribution', max_length=255),
        ),
    ]
