# Generated by Django 4.2.8 on 2024-01-01 07:56

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpowermentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('programs_and_activities', wagtail.fields.RichTextField(blank=True)),
                ('community_success_stories_intro', wagtail.fields.RichTextField(blank=True)),
                ('get_involved', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Empowerment Page',
                'verbose_name_plural': 'Empowerment Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
