# Generated by Django 4.2.8 on 2024-03-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0002_volunteerdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerdata',
            name='opportunity_name',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
