# Generated by Django 4.2.8 on 2024-03-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0003_volunteerdata_opportunity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerdata',
            name='phone_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
