# Generated by Django 4.2.8 on 2024-03-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0006_donationtypes_delete_typesofdonations'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('suffix', models.CharField(max_length=5)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('motive', models.TextField()),
            ],
        ),
    ]
